### ISSUE TITLE
error de compilacion

### ISSUE THREAD

**Issue by Piero15** [ZHomeSlice/Simple_MPU6050#14]
al intentar compilar el programa me sale un error que es el siguiente 

d from C:\Users\Pieri\OneDrive\Documentos\Arduino\libraries\Simple_MPU6050-master/Simple_MPU6050.h:7:0,
                 from C:\Users\Pieri\OneDrive\Documentos\Arduino\libraries\Simple_MPU6050-master\Examples\Simple_MPU6050_Example\Simple_MPU6050_Example.ino:3:
C:\Users\Pieri\OneDrive\Documentos\Arduino\libraries\Simple_MPU6050-master/DMP_Image.h: In member function 'int VectorInt16::normalize()':
C:\Users\Pieri\OneDrive\Documentos\Arduino\libraries\Simple_MPU6050-master/DMP_Image.h:581:44: error: cannot convert 'VectorInt16' to 'int' in return
     return VectorInt16(x /= m,y /= m,z /= m);
                                            ^
In file included from C:\Users\Pieri\OneDrive\Documentos\Arduino\libraries\Simple_MPU6050-master/Simple_MPU6050.h:7:0,
                 from C:\Users\Pieri\OneDrive\Documentos\Arduino\libraries\Simple_MPU6050-master\Examples\Simple_MPU6050_Example\Simple_MPU6050_Example.ino:3:
C:\Users\Pieri\OneDrive\Documentos\Arduino\libraries\Simple_MPU6050-master/DMP_Image.h: In member function 'int VectorInt16::rotate(Quaternion*)':
C:\Users\Pieri\OneDrive\Documentos\Arduino\libraries\Simple_MPU6050-master/DMP_Image.h:613:35: error: cannot convert 'VectorInt16' to 'int' in return
     return VectorInt16(p.x,p.y,p.z);
                                   ^
C:\Users\Pieri\OneDrive\Documentos\Arduino\libraries\Simple_MPU6050-master/DMP_Image.h: In member function 'int VectorFloat::normalize()':
C:\Users\Pieri\OneDrive\Documentos\Arduino\libraries\Simple_MPU6050-master/DMP_Image.h:651:45: error: cannot convert 'VectorFloat' to 'int' in return
     return VectorFloat( x /= m,y /= m,z /= m);
                                             ^
C:\Users\Pieri\OneDrive\Documentos\Arduino\libraries\Simple_MPU6050-master/DMP_Image.h: In member function 'int VectorFloat::rotate(Quaternion*)':
C:\Users\Pieri\OneDrive\Documentos\Arduino\libraries\Simple_MPU6050-master/DMP_Image.h:674:37: error: cannot convert 'VectorFloat' to 'int' in return
      return VectorFloat( p.x,p.y,p.z);

estoy intentando compilar el mismo programa de ejemplo y no estoy seguro pero creo q es un problema de la misma libreria quisiera saber como podria solucionarlo gracias de ante mano

**Comment by ZHomeSlice** [comment]
Tryit now :)
