### ISSUE TITLE
Difficulty Compiling

### ISSUE THREAD

**Issue by anmol1980** [ZHomeSlice/Simple_MPU6050#20]
Hi Z,

I have been using your library since last year, and it works well most of the time. However, sometime it hangs up. I know some programming, but am by no means a s/w engineer.

I am using Arduino Uni board. I have updated the Arduino AVR Board using the Board Manager to version 1.8.4. I am assuming that this will update Wire library to the latest version that includes setWireTimeout that you have discussed with other folks.

When I try to compile your Simple_MPU6050_Basic_Example code, I get the following error. Could you kindly help me figure out the reason for error.

Thanks,
Anmol

Arduino: 1.8.11 (Mac OS X), Board: "Arduino Uno"

/Users/Anmol/Documents/Arduino/libraries/Simple_MPU6050/Simple_MPU6050.cpp: In member function 'int8_t Simple_MPU6050::GetCurrentFIFOPacket(uint8_t*, uint8_t)':
/Users/Anmol/Documents/Arduino/libraries/Simple_MPU6050/Simple_MPU6050.cpp:203:32: error: 'I2CDEVLIB_WIRE_BUFFER_LENGTH' was not declared in this scope
                  uint8_t Trash[I2CDEVLIB_WIRE_BUFFER_LENGTH];
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/Anmol/Documents/Arduino/libraries/Simple_MPU6050/Simple_MPU6050.h:31:0,
                 from /Users/Anmol/Documents/Arduino/libraries/Simple_MPU6050/Simple_MPU6050.cpp:28:
/Users/Anmol/Documents/Arduino/libraries/Simple_MPU6050/Simple_MPU6050.cpp:210:40: error: 'Trash' was not declared in this scope
        FIFO_READ((uint8_t)RemoveBytes, Trash);
                                        ^
/Users/Anmol/Documents/Arduino/libraries/Simple_MPU6050/MPU_ReadMacros.h:304:91: note: in definition of macro 'FIFO_READ'
 #define FIFO_READ(PacketLength, Data)      MPUi2cReadBytes(0x74, PacketLength, (uint8_t *)Data)  //   Read/Write command provides Read or Write operation for the FIFO.
                                                                                           ^~~~
Multiple libraries were found for "Simple_MPU6050.h"
 Used: /Users/Anmol/Documents/Arduino/libraries/Simple_MPU6050
 Not used: /Users/Anmol/Documents/Arduino/libraries/Simple_MPU6050_archive
exit status 1
Error compiling for board Arduino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by ZHomeSlice** [comment]
@anmol1980 

That's Great! I have found this library to be much simpler to use with my projects. I'm glad you are able to use it. I'm a hobbyist I love electronics and know a little C. This has been a multi-year project creating this library. 

I have pinned The freezing down to the wire library also and the setWireTimeout seems to resolve it.

So for the errors
1) I2CDEVLIB is by  Jeff Rowberg he created the i2cdevlib, I would update his library as I have seen this topic discussed and I believe it has been resolved.
[The i2cdev library can be found here ](https://github.com/jrowberg/i2cdevlib/tree/da71c0469cd63316963a9871f732f40d624680b0/Arduino/I2Cdev)
My library uses his library as a base and as you can see with my class definition `class Simple_MPU6050 : public I2Cdev {` it extends his library so every function in his library becomes native to my library.
within jeffs latest i2cdev.h file we find:
```
#ifndef I2CDEVLIB_WIRE_BUFFER_LENGTH
    #if defined(I2C_BUFFER_LENGTH)
        // Arduino ESP32 core Wire uses this
        #define I2CDEVLIB_WIRE_BUFFER_LENGTH I2C_BUFFER_LENGTH
    #elif defined(BUFFER_LENGTH)
        // Arduino AVR core Wire and many others use this
        #define I2CDEVLIB_WIRE_BUFFER_LENGTH BUFFER_LENGTH
    #elif defined(SERIAL_BUFFER_SIZE)
        // Arduino SAMD core Wire uses this
        #define I2CDEVLIB_WIRE_BUFFER_LENGTH SERIAL_BUFFER_SIZE
    #else
        // should be a safe fallback, though possibly inefficient
        #define I2CDEVLIB_WIRE_BUFFER_LENGTH 32
    #endif
#endif
```
This resolves the I2CDEVLIB_WIRE_BUFFER_LENGTH issue.

As for the other issues
Multiple libraries were found for "Simple_MPU6050.h"
indicates that you have multiple Simple_MPU6050.h files that the compiler is picking from. You will want to get the latest version and remove the others and come back if you still have compiling issues.

Z
