### ISSUE TITLE
Can't compile missing definitions

### ISSUE THREAD

**Issue by imk2021** [ZHomeSlice/Simple_MPU6050#21]
Hello,
Just pulled this lib and really look very comprehensive.
However tried to compile it for UNO with Arduino IDE V2 RC2 and get following errors:

 D:\NewDev\ARDUINO\Gyro\Gyro-Test6\Simple_MPU6050.cpp: In member function 'int8_t Simple_MPU6050::GetCurrentFIFOPacket(uint8_t*, uint8_t)':
D:\NewDev\ARDUINO\Gyro\Gyro-Test6\Simple_MPU6050.cpp:200:32: error: 'I2CDEVLIB_WIRE_BUFFER_LENGTH' was not declared in this scope
                  uint8_t Trash[I2CDEVLIB_WIRE_BUFFER_LENGTH];
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from D:\NewDev\ARDUINO\Gyro\Gyro-Test6\Simple_MPU6050.h:28:0,
                 from D:\NewDev\ARDUINO\Gyro\Gyro-Test6\Simple_MPU6050.cpp:25:
D:\NewDev\ARDUINO\Gyro\Gyro-Test6\Simple_MPU6050.cpp:207:40: error: 'Trash' was not declared in this scope
        FIFO_READ((uint8_t)RemoveBytes, Trash);
                                        ^
D:\NewDev\ARDUINO\Gyro\Gyro-Test6\MPU_ReadMacros.h:301:91: note: in definition of macro 'FIFO_READ'
 #define FIFO_READ(PacketLength, Data)      MPUi2cReadBytes(0x74, PacketLength, (uint8_t *)Data)  //   Read/Write command provides Read or Write operation for the FIFO.
                                                                                           ^~~~
Compilation error: exit status 1}

Hope this contribution helps, have a good Christmas abd New Year.. IMK

**Comment by ZHomeSlice** [comment]
Thanks :)
Your missing deffinition: I2CDEVLIB_WIRE_BUFFER_LENGTH

I2CDEVLIB is by Jeff Rowberg he created the i2cdevlib, I would update his library as I have seen this topic discussed and I believe it has been resolved.
[The i2cdev library can be found here](https://github.com/jrowberg/i2cdevlib/tree/da71c0469cd63316963a9871f732f40d624680b0/Arduino/I2Cdev)
My library uses his library as a base and as you can see with my class definition `class Simple_MPU6050 : public I2Cdev {` it extends his library so every function in his library becomes native to my library.
within jeffs latest i2cdev.h file we find:
```
#ifndef I2CDEVLIB_WIRE_BUFFER_LENGTH
    #if defined(I2C_BUFFER_LENGTH)
        // Arduino ESP32 core Wire uses this
        #define I2CDEVLIB_WIRE_BUFFER_LENGTH I2C_BUFFER_LENGTH
    #elif defined(BUFFER_LENGTH)
        // Arduino AVR core Wire and many others use this
        #define I2CDEVLIB_WIRE_BUFFER_LENGTH BUFFER_LENGTH
    #elif defined(SERIAL_BUFFER_SIZE)
        // Arduino SAMD core Wire uses this
        #define I2CDEVLIB_WIRE_BUFFER_LENGTH SERIAL_BUFFER_SIZE
    #else
        // should be a safe fallback, though possibly inefficient
        #define I2CDEVLIB_WIRE_BUFFER_LENGTH 32
    #endif
#endif
```
This resolves the I2CDEVLIB_WIRE_BUFFER_LENGTH issue.

Z
