### ISSUE TITLE
Could not get access to Embedded MotionDriver 6.12

### ISSUE THREAD

**Issue by nilavghosh** [ZHomeSlice/Simple_MPU6050#24]
HI @ZHomeSlice . This is a great repo and thanks for sharing it. I am however unable to get the Embedded MotionDriver 6.12 library from the Invensense site. Is it possible for you to share it via a drive link that i can utilise. WIll be great help.

**Comment by ZHomeSlice** [comment]
https://github.com/x893/MotionDriver6
should be the same
