### ISSUE TITLE
Possibility of providing DMP at rate higher than 10ms?

### ISSUE THREAD

**Issue by lekoook** [ZHomeSlice/Simple_MPU6050#5]
Is it possible to configure the MPU6050 to provide DMP values at a rate that is higher than 100Hz(10ms)?

Additionally, is the rate of the fifo callback dependent on how often dmp_read_fifo() is called? So if I don't call it often enough, would the callback rate drop?

**Comment by ZHomeSlice** [comment]
Faster than 10ms? 
The answer is yes. 
Now I haven't successfully captured the data at 200 hz.
i2c bus tends to be to slow to keep up

To achieve the faster rate you will need to modify the firmware image. The exact change will require you to research the example code provided by invensence they provide a function which configures the embedded firmware to deliver data to the fifo buffer at the higher rates.
Z
